name: GHA subワークフロー

on:
  workflow_dispatch:
    inputs:
      env:
        description: "環境を選んでください。"
        type: choice
        options:
          - prd
          - stg
          - dev
  repository_dispatch:
    types: [test_result]

jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - name: get env
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "env=${{ github.event.inputs.env }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "env=${{ github.event.client_payload.env }}" >> $GITHUB_ENV
          fi
      - name: output env
        run: |
          echo 'Your choice is ${{ env.env }}.'
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
